apiVersion: argoproj.io/v1alpha1
kind: ApplicationList
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: cnpg-operator
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      sources:
        - repoURL: https://cloudnative-pg.io/charts
          chart: cloudnative-pg
          targetRevision: 0.27.0
          helm:
            valueFiles:
              - $charts/apps/cnpg/values.yaml
        - repoURL: https://github.com/overburrow/charts.git
          targetRevision: main
          ref: charts
      destination:
        server: https://kubernetes.default.svc
        namespace: cnpg-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: cnpg-cluster
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/overburrow/charts.git
          targetRevision: main
          recurse: true
          path: apps/cnpg/instances
      destination:
        server: https://kubernetes.default.svc
        namespace: database
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
