{{- range .Values.routes }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  parentRefs:
    {{- if or (eq .visibility "private") (eq .visibility "both") }}
    - name: private-gateway
      namespace: networking
    {{- end }}

    {{- if or (eq .visibility "public") (eq .visibility "both") }}
    - name: public-gateway
      namespace: networking
    {{- end }}
  hostnames:
    - {{ .hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .serviceName }}
          port: {{ .servicePort | default 80 }}
---
{{- end }}
